### ISSUE TITLE
Fetch miner info from stack-blockchain

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/miningbot-client#14]
**Is your feature request related to a problem? Please describe.**
The mining bot client should analyze the detail information about miner operation, like:
- How much bitcoin other miners burnt in last cycle?
- Who won the block in last cycle? What is the VRF function returns in last cycle?

**Describe the solution you'd like**
The stacks-blockchain connect *bitcoind*, a test bitcoin node of bitcoin network. Because the burn operation will reflect to "sending commit info and certain bitcoin to a bitcoin address", so we could track the bitcoin address and see who and what another address sent in the last cycle.

Pascal in *Blockstack Community* gives me another option:
The stacks-blockchain is a blockchain infrastructure, it has a database behind the blockchain. He said I can use database operation to get the information stored in block(like transaction). But referred to "how much other miners paid", it should be fetched by *bitcoind* absolutely, because the consensus information could not be fetched in stacks-blockchain.

**Describe alternatives you've considered**
- If we could launch our own test node and synced with "bitcoind.krypton.blockstack.org". Then monitoring each block, get how much other miners burnt in the last cycle.

**Additional context**
- In the mainnet, we could run a bitcoin lite node to monitoring the confirm block related to stacks-mining.

**Comment by tyGavinZJU** [comment]
like "*how much bitcoin other miners burnt in any certain cycles?*"

**Comment by tyGavinZJU** [comment]
Use https://github.com/tyGavinZJU/stacks-dump as rpc server, deployed at 8.210.105.204 Visit by http://8.210.105.204:23456/minerList (Visit will be super slow because of the low configuration of server)

**Comment by SherLzp** [comment]
fixed by #30
