### ISSUE TITLE
[Wallet] BTC/STX wallet account importing

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/miningbot-client#5]
**Is your feature request related to a problem? Please describe.**
Adding Wallet importing module.

**Describe the solution you'd like**
1. Importing the private key by Mnemonic（24 words which could support be copied/pasted by terminal）
2. Encrypt the private key by user defined key.
3. Save the encrypted private key to LocalStorage

**Describe alternatives you've considered**

**Additional context**
Each STX address is corresponding to a BTC address, show the connection in frontend.

**Comment by tyGavinZJU** [comment]
@SherLzp

**Comment by SherLzp** [comment]
fixed by https://github.com/Daemon-Technologies/miningbot-client/pull/11
