### ISSUE TITLE
locale en-US/zh-CN switch problem

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/miningbot-client#8]
**Describe the bug**
Cannot switch locale en-US&zh-CN in *config/config.ts*

**Steps To Reproduce**
**mining-client** page will show this problem

**Expected behavior**
Switch en-US&zh-CN by Button in TopBar

**Additional context**

**Comment by tyGavinZJU** [comment]
@SherLzp

**Comment by SherLzp** [comment]
fixed by #33
