### ISSUE TITLE
[login] wallet private key encrypted by login password 

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/miningbot-client#9]
**Is your feature request related to a problem? Please describe.**
Referred to Metamask, user have to input his password in the first page, this password will be used to encrypt wallet private key to localStorage.

**Describe the solution you'd like**
Referred to Metamask

**Describe alternatives you've considered**

**Additional context**
Login password will be stored in localStorage and cannot be restored.

**Comment by SherLzp** [comment]
fixed by #23
